#!/bin/bash
# vim: set tabstop=4:

SELF="${0##*/}"
HERE="$(cd $(dirname "$0"); pwd)"

SEARCH="$1"

GITHUB_USER="${SELF#*_}"

LISTOFREPOSITORIES="$(PWD)/list_of_repositories"

get_listofrepositories_onpage()
{
	_LINK="$1"
	_PAGE="$2"

	_OUT=tmp.output

	wget "${_LINK}" -O - -q	 > ${_OUT}
	
	cat ${_OUT}															| \
			grep codeRepository 										| \
			cut -d\" -f2												| \
			cut -d/  -f3												| \
			cat >>$LISTOFREPOSITORIES

	cat ${_OUT}															| \
			tr '>' '\n'  												| \
			grep nofollow												| \
			grep after=													| \
			cut -d'"' -f4 

	rm ${_OUT}
}


get_listofrepositories()
{
	>$LISTOFREPOSITORIES

	_THIS="https://github.com/${GITHUB_USER}?tab=repositories"
	_PAGE=0

	printf "01. get list of repositories from page "

	while [[ -n "$_THIS" ]]
	do
		(( _PAGE=$_PAGE + 1))

		printf "%3d" "$_PAGE"
		_NEXT="$(get_listofrepositories_onpage "$_THIS" "$_PAGE")"

		_THIS="$_NEXT"
	done

	sort -o $LISTOFREPOSITORIES $LISTOFREPOSITORIES
}

if [ "$1" == "--list" ]; then
	MODE=VIEW

	get_listofrepositories

	cat $LISTOFREPOSITORIES

	exit
elif [ "$1" == "--clone" ]; then
	MODE=CLONE

	if [ "$2" == "" ]; then
		get_listofrepositories
	else
		echo "https://github.com/${GITHUB_USER}/${2}" >$LISTOFREPOSITORIES
	fi
else
	MODE=CLONE
	get_listofrepositories
fi

#
#
#
if [ "$MODE" == "CLONE" ]; then
	cd       $HERE
	mkdir -p repositories/$GITHUB_USER
	cd       repositories/$GITHUB_USER

	touch -t 0101010101 *

	printf "02. clone repositories\n"
fi

#
#
#
cat $LISTOFREPOSITORIES | while read REP
do	
	if [ "$MODE" == "CLONE" ]; then
		RESULT=$(git clone git@github.com:${GITHUB_USER}/${REP}.git 2>&1)
		RETURN=$?
	
		touch ${REP}

		if [ $RETURN == 128 ]; then
			DIR=$(echo $RESULT | cut -d\' -f2)

			echo "Repository Already cloned: '$REP' to $DIR, $(cd $DIR; git pull)"
		else	
			echo "Repository Cloned:         '$REP' cloned."
		fi
	fi
done

rm $LISTOFREPOSITORIES
